version: '2'
services:
  proxy_pool:
    volumes:
     - ..:/usr/src/app
    ports:
     - "5010:5010"
    image: "1again/proxy_pool"
  proxy_pool_db:
    ports:
     - "27017:27017"
    image: "mongo"